---
jobs:
  include:
    - name: High Sierra
      os: osx
      osx_image: xcode10.1
      language: shell

before_install:
  # Install pip
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H /usr/bin/python
  - which pip
  - pip --version

  # Setup virtualenv
  - sudo -H pip install -U virtualenv --ignore-installed six
  - virtualenv --version
  - virtualenv ~/.venv
  - source ~/.venv/bin/activate

install:
  # Dependencies
  - >-
    pip install ansible
    ansible-lint
    yamllint

  # Check versions
  - ansible --version
  - ansible-lint --version
  - yamllint --version

script:
  # lint
  - yamllint $TRAVIS_BUILD_DIR/
  - ansible-lint

  # Run playbook
  - make install

  # Check configuration
  - carthage version
  - fastlane --version
  - pod --version
  - rome --version
  - rvm list
  - swiftlint version
  - source ~/.bashrc

  - echo $LC_ALL
