---
sudo: required
language: generic

matrix:
  include:
    # Mojave (Latest)
    - os: osx
      osx_image: xcode11.3
    # High Sierra
    - os: osx
      osx_image: xcode10.1

script:
  - echo "Initial project build."
