---
sudo: required
jobs:
  include:
    - name: High Sierra
      os: osx
      osx_image: xcode10.1
      language: minimal
      env: ANSIBLE_VERSION='<2.9.0'

before_install:
  # Install pip
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H /usr/bin/python
  - which pip
  - pip --version

  # Setup virtualenv
  - sudo -H pip install -U virtualenv --ignore-installed six
  - virtualenv --version
  - virtualenv .venv
  - source .venv/bin/activate

install:
  # Dependencies
  - >-
    pip install "ansible${ANSIBLE_VERSION}"
    ansible-lint
    testinfra
    yamllint

  # Check versions
  - ansible --version
  - ansible-lint --version
  - yamllint --version

script:
  # lint
  - yamllint .
  - ansible-lint

  # Basic role syntax check
  - ansible-playbook playbook.yml -i inventory --syntax-check
  - ansible-playbook playbook.yml -i inventory --check
