---
- hosts: localhost
  connection: local
  vars_files:
    - vars/homebrew.yml
    - vars/gems.yml
    - vars/mas.yml
  roles:
    - role: geerlingguy.homebrew
      tags: [homebrew]
    - role: martianplatypus.ruby_mac
      tags: [ruby, rvm]
    - role: fastlane
      tags: [fastlane]
    - role: rome
      tags: [rome]
    - role: geerlingguy.mas
      tags: [mas]
    - role: xcode
      tags: [xcode]
    - role: swiftlint
      tags: [swiftlint]
