---
- name: Get Xcode required MacOS version
  shell: |
    set -o pipefail
    mas info '{{ xcode_app_id }}' | awk '/Minimum OS:/{ print $3 }'
  register: xcode_minimum_os_required
  changed_when: ansible_distribution_version is version(xcode_minimum_os_required.stdout, '>=')

- name: Install Xcode if compatible
  command: mas install "{{ xcode_app_id }}"
  when:
    - xcode_minimum_os_required.stdout is defined
    - ansible_distribution_version is version(xcode_minimum_os_required.stdout, '>=')
